//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TermProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class app
    {
        public app()
        {
            this.screens = new HashSet<screen>();
            this.comments = new HashSet<comment>();
        }
    
        public int Id { get; set; }
        public string aname { get; set; }
        public string afile { get; set; }
        public string Icon { get; set; }
        public string discription { get; set; }
        public string type { get; set; }
        public Nullable<int> price { get; set; }
        public string catagories { get; set; }
        public System.DateTime uploaddate { get; set; }
        public string size { get; set; }
        public Nullable<int> like { get; set; }
        public Nullable<int> rate { get; set; }
        public Nullable<int> rperson { get; set; }
        public string newthing { get; set; }
        public int numinstall { get; set; }
        public string currentversion { get; set; }
        public int uid { get; set; }
        public string status { get; set; }
    
        public virtual user user { get; set; }
        public virtual ICollection<screen> screens { get; set; }
        public virtual ICollection<comment> comments { get; set; }
    }
}
