//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TermProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.apps = new HashSet<app>();
            this.comments = new HashSet<comment>();
        }
    
        public int Id { get; set; }
        public string username { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string type { get; set; }
        public string dob { get; set; }
        public string Gender { get; set; }
        public string contactno { get; set; }
        public string address { get; set; }
        public string accountno { get; set; }
        public string pic { get; set; }
        public Nullable<int> uid { get; set; }
        public string weblink { get; set; }
    
        public virtual ICollection<app> apps { get; set; }
        public virtual ICollection<comment> comments { get; set; }
        public virtual uni uni { get; set; }
    }
}
